src/Entity/Avenant.php
<?php

namespace App\Entity;

use Doctrine\ORM\Mapping as ORM;
use Doctrine\ORM\Mapping\PrePersist;

/**
 * @ORM\Entity(repositoryClass="App\Repository\AvenantRepository")
 * @ORM\HasLifecycleCallbacks()
 * 
 */
class Avenant
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $Libelle;

    /**
     * @ORM\Column(type="float")
     */
    private $MontantAvenant;

    /**
     * @ORM\ManyToOne(targetEntity="App\Entity\Clients", inversedBy="avenants")
     * @ORM\JoinColumn(nullable=false)
     */
    private $Client;

    /**
     * @ORM\Column(type="datetime")
     */
    private $date;
    
    /**
     * @ORM\PrePersist
     */
    public function prePersist()
    {
   
        if(empty($this->date))
        {
            $this->date = new \DateTime();
        }
      
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getLibelle(): ?string
    {
        return $this->Libelle;
    }

    public function setLibelle(string $Libelle): self
    {
        $this->Libelle = $Libelle;

        return $this;
    }

    public function getMontantAvenant(): ?float
    {
        return $this->MontantAvenant;
    }

    public function setMontantAvenant(float $MontantAvenant): self
    {
        $this->MontantAvenant = $MontantAvenant;

        return $this;
    }

    public function getClient(): ?Clients
    {
        return $this->Client;
    }

    public function setClient(?Clients $Client): self
    {
        $this->Client = $Client;

        return $this;
    }

    public function getDate()
    {
        return $this->date;
    }

    public function setDate( $date): self
    {
        $this->date = $date;

        return $this;
    }
}

src/Controller/BoisController.php
<?php

namespace App\Controller;

use App\Repository\FinitionDetailsRepository;
use App\Repository\FinitionRepository;
use App\Repository\ProduitsRepository;
use App\Repository\TypesRepository;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\Routing\Annotation\Route;

class BoisController extends AbstractController
{
    /**
     * @Route("/bois", name="boisPage")
     */
    public function index(TypesRepository $typeCa)
    {
       $type = $typeCa->findBy(['Categories' => "2" ]);
       $typee = $typeCa->findAll();
        return $this->render('bois/index.html.twig',[
            'types' => $type,
            'typee' => $typee
        ]);
    }

    /**
     * @Route("/boisDetails/{id}", name="boisDetails")
     * 
     */
    public function boisDetailss(ProduitsRepository $prod ,$id,TypesRepository $typeCa,FinitionRepository $repo)
    {

       $produi = $prod->findOneBy(['id' => $id ]);
       $type = $typeCa->findAll();
       $finideatils = $repo->findAll();
        return $this->render('bois/produitDetails.html.twig',[
           'produits' => $produi,
           'typee' => $type,
           'finitions' => $finideatils
        ]);
    }
}

templates/bois/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Travaux en bois{% endblock %}
 {% block stylesheets %}

 
 {% endblock %}
{% block body %}
    <section class="page-title-section">
        <div class="container">
            <div class="row">
                <div class="col-xs-12">
                    <div class="page-header-wrap">
                        <div class="page-header">
                            <h4>Produits en Bois</h4>
                        </div>
                        <ol class="breadcrumb">
                            <li><a href="#">Accueil</a></li>
                            <li class="active">Bois</li>
                        </ol>
                    </div>
                </div>
            </div>
        </div>
    </section>
    <div class="container">
   {% include "partials/produits.html.twig" %}
    </div>
     {% block javascripts %}
 

  <!-- Template Custom JavaScript File -->
     {% endblock %}
{% endblock %}

templates/bois/produitDetails.html.twig
{% extends "base.html.twig" %}				
{% block title %}Menuiserie Aluminium{% endblock %} 
{% block stylesheets %}
{% endblock %}
		{% block body %}
<section class="page-title-section ">
	<div class="container">
		<div class="row">
			<div class="col-xs-12">
				<div class="page-header-wrap">
					<div class="page-header">
						<h1>Détails Produits  </h1>
					</div>
					<ol class="breadcrumb">
						<li><a href="#">Accueil</a></li>
						<li class="active">Produit <span class="text-danger"> {{ produits.slug | upper  }} </span>
						</li>
					</ol>
				</div>
			</div>
		</div>
	</div>
</section>
<!-- blog-section -->
{% include "partials/detailspro.html.twig" %}

{% for finition in finitions %}

<section class="container ">
	<h3 class="">{{ finition.libelle }}</h3>

     <div class="partner-section">
		<div class="row row-content">
		<div class="col-md-12">
			<div class="owl-carousel partner-carousel">
				{% for finitionDetails in finition.finitionDetails %}
				<div class="item">
				<h6 class="text-center">{{ finitionDetails.designation }}</h6>
					<a href="#" >
						<img class="img-fluid m-5"  src="{{ asset('upload/'~ finitionDetails.image ) }}"   alt="">
					</a>
				</div>{% endfor %}
			</div>
			<div class="partner-carousel-navigation">
				<a class="prev"><i class="fa fa-angle-left"></i></a>
				<a class="next"><i class="fa fa-angle-right"></i></a>
			</div><!-- /.partner-carousel-navigation -->
		</div><!-- /.col-md-12 -->
		</div><!-- /.row -->
	</div><!-- /.partner-section -->
</section>
<br>
{% endfor %}  
{% endblock %}           
                